### ISSUE TITLE
[FEAT] 이메일 인증, 로그아웃 기능 구현

### ISSUE THREAD

**Issue by rosieisor** [Hanium2023-WeB/starD-backend-refactoring#14]
### 💼 작업 설명

- 회원 가입 시 이메일 인증 기능 구현
- 로그아웃 기능 구현

### ✅ To-do

- [x] 이메일 인증 기능 구현
- [ ] 로그아웃 기능 구현

**Comment by rosieisor** [comment]
`application.yml` 아래와 같이 수정 필요합니다!

```
spring:
  mail:
    host: smtp.naver.com
    username: [naver 아이디]@naver.com
    password: [비밀번호]
```
